@startuml

participant Bullet
participant Tank
entity GameManager
entity UIManager

Bullet -> Tank : Hit

create participant Explosion
Tank -> Explosion : Generate

Tank -> GameManager : Tell destroyed

destroy Tank

hnote over GameManager
    Time passed
endhnote

alt if Only one tank left
    hnote over GameManager
        Game Set!
    endhnote

    GameManager -> UIManager : Command

    hnote over UIManager
        Show Game set UI
    endhnote
end

@enduml